name: CI

on:
  workflow_dispatch: 
    inputs:
      version:
        type: string
        default: "1.0.0"
        required: true

      release_type:
        type: choice
        options: [ patch, minor, major ]
        default: "patch"


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "{{ inputs.version }}"
      - run: echo "{{ inputs.release_type }}"
      - run: echo "{{ github.run_number }}"
      - run: echo "build_date=$(date +%F)" >> "$GITHUB_OUTPUT"

  announce:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo "build_date:${{ needs.prepare.outputs.build_date }}"
