name: CI Fix me
on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo files
        run: ls -la
      - name: Runs the hello script
        run: bash scripts/hello.sh
