name: Q6 

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        id: greet
      - uses: ./.github/actions/greet
        with:
          name: ${{ github.actor }}
          env_name: ${{ inputs.target_env }}

      - run: |
          echo "${{ steps.greet.outputs.greeting }}"
          echo "Deploying to ${{ inputs.target_env }}... done."
